Add grafana metrics dashboard
Trendyol/go-dcp-elasticsearch pull request #75
Opened 2024-07-17 19:33 UTC by sefacan

2024-07-18 07:22 UTC, erayarslan approved these changes

2024-07-18 07:27 UTC, Abdulsametileri requested changes

2024-07-18 07:27 UTC, Abdulsametileri commented on dashboards/metrics.json
> +{
Could you provide screen shoot?

2024-07-18 08:12 UTC, Abdulsametileri commented
This dashboard is not applicable for open source (it includes our logics) 
we need to prepare generic dashboard like https://github.com/Trendyol/kafka-konsumer/tree/v2/examples/with-grafana
could you change like that

2024-07-22 08:47 UTC, sefacan commented on dashboards/metrics.json
> +{
I have added.

2024-07-22 08:48 UTC, sefacan commented
> This dashboard is not applicable for open source (it includes our logics) we need to prepare generic dashboard like https://github.com/Trendyol/kafka-konsumer/tree/v2/examples/with-grafana could you change like that

Ok I will provide

2024-07-25 09:09 UTC, sefacan commented
> This dashboard is not applicable for open source (it includes our logics) we need to prepare generic dashboard like https://github.com/Trendyol/kafka-konsumer/tree/v2/examples/with-grafana could you change like that

Hello again, I have added quick docker-compose example for grafana.

2024-07-30 14:59 UTC, Abdulsametileri commented
Sorry for my late response, lgtm, could you solve the conflict?

2024-08-04 06:02 UTC, closed without merging